version: '3'
services:
  api:
    build: ..
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
  postgres:
    image: postgres   
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
